import { loadYaml } from './yamlReader.js';

const locator = loadYaml('locators');

export const LOGIN_EMAIL_INPUT = locator.LOGIN_EMAIL_INPUT;
export const LOGIN_PASSWORD_INPUT = locator.LOGIN_PASSWORD_INPUT;
export const LOGIN_BUTTON = locator.LOGIN_BUTTON;
export const HOMEPAGE_WOMEN_CATEGORY_LINK = locator.HOMEPAGE_WOMEN_CATEGORY_LINK;
export const HOMEPAGE_MEN_CATEGORY_LINK = locator.HOMEPAGE_MEN_CATEGORY_LINK;
export const HOMEPAGE_KIDS_CATEGORY_LINK = locator.HOMEPAGE_KIDS_CATEGORY_LINK;
export const ADD_TO_CART_DRESS_ITEM = locator.ADD_TO_CART_DRESS_ITEM;
export const ADD_TO_CART_TOPS_ITEM = locator.ADD_TO_CART_TOPS_ITEM;
export const ADD_TO_CART_SAREE_ITEM = locator.ADD_TO_CART_SAREE_ITEM;
export const ADD_TO_CART_SLEEVES_DRESS_ITEM = locator.ADD_TO_CART_SLEEVES_DRESS_ITEM;
export const ADD_TO_CART_SUMMER_WHITE_TOP_ITEM = locator.ADD_TO_CART_SUMMER_WHITE_TOP_ITEM;
export const ADD_TO_CART_BEAUTIFUL_PEAQUICK_BLUE_COTTON_LINEN_SAREE_ITEM = locator.ADD_TO_CART_BEAUTIFUL_PEAQUICK_BLUE_COTTON_LINEN_SAREE_ITEM;
export const ADD_TO_CART_CONTINUE_SHOPPING_BUTTON = locator.ADD_TO_CART_CONTINUE_SHOPPING_BUTTON;