name: Automation Framework CI

on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: "CICD job"
        required: true
        default: "false"

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  selenium-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    name: Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.2

      - name: Install Selenium Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install allure-robotframework
          pip install pyyaml

      - name: Create dev environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "BROWSER: ${{ secrets.BROWSER }}" >> variables/env_dev.yaml
          echo "REGISTER_SUCCESS_REDIRECT_LINK: ${{ secrets.REGISTER_SUCCESS_REDIRECT_LINK }}" >> variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "VALID_USERNAME: ${{ secrets.VALID_USERNAME }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_ERROR_MESSAGE: ${{ secrets.INVALID_EMAIL_ERROR_MESSAGE }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V2: ${{ secrets.INVALID_EMAIL_V2 }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V2_ERROR_MESSAGE: ${{ secrets.INVALID_EMAIL_V2_ERROR_MESSAGE }}" >> variables/env_dev.yaml
          echo "REGISTERED_EMAIL: ${{ secrets.REGISTERED_EMAIL }}" >> variables/env_dev.yaml

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Selenium Tests
        run: |
          robot \
          --listener allure_robotframework \
          --outputdir output \
          tests/web/selenium
      
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-allure
          path: output/allure-results
          if-no-files-found: ignore



  playwright-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    name: Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.2

      - name: Install Playwright Dependencies
        run: |
          pip install robotframework
          pip install robotframework-browser
          pip install allure-robotframework
          pip install pyyaml

      - name: Install Playwright Browsers
        run: |
          rfbrowser init

      - name: Create dev environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "BROWSER_FOR_PLAYWRIGHT: ${{ secrets.BROWSER_FOR_PLAYWRIGHT }}" >> variables/env_dev.yaml
          echo "HEADLESS: ${{ secrets.HEADLESS }}" >> variables/env_dev.yaml
          echo "VALID_USERNAME: ${{ secrets.VALID_USERNAME }}" >> variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V3: ${{ secrets.INVALID_EMAIL_V3 }}" >> variables/env_dev.yaml
          echo "REGISTER_PASSWORD: ${{ secrets.REGISTER_PASSWORD }}" >> variables/env_dev.yaml
      - name: Run Playwright Tests
        run: |
          robot \
          --listener allure_robotframework \
          --outputdir output \
          tests/web/playwright
      
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-allure
          path: output/allure-results
          if-no-files-found: ignore



  playwright-ts-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    name: Playwright Tests (TypeScript)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13

      - name: Install dependencies
        run: |
          npm install
          npm install -D allure-playwright

      - name: Install dependencies
        run: |
          npm install

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      - name: Create environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}" >> variables/env_dev.yaml
          ls -la variables
          cat variables/env_dev.yaml

      - name: Run Playwright TypeScript Tests
        run: |
          npx playwright test \
          --reporter=line,allure-playwright

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-allure
          path: output/allure-results
          if-no-files-found: ignore

# -------------------------------
# Merge + Generate Allure
# -------------------------------


  generate-allure-report:
    if: always()

    needs:
      - selenium-tests
      - playwright-tests
      - playwright-ts-tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------
    # Download artifacts
    # -------------------------

    - name: Download Selenium Results
      uses: actions/download-artifact@v4
      with:
        name: selenium-allure
        path: allure-results/selenium
      continue-on-error: true

    - name: Download Playwright Results
      uses: actions/download-artifact@v4
      with:
        name: playwright-allure
        path: allure-results/playwright
      continue-on-error: true

    - name: Download Playwright TS Results
      uses: actions/download-artifact@v4
      with:
        name: playwright-ts-allure
        path: allure-results/playwright-ts
      continue-on-error: true

    # -------------------------
    # Merge results
    # -------------------------

    - name: Merge Results
      run: |
        mkdir -p merged-results
        cp -r allure-results/*/* merged-results/ || true

    # -------------------------
    # Generate Allure report
    # -------------------------

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Allure CLI
      run: |
        npm install -g allure-commandline

    - name: Generate Report
      run: |
        allure generate merged-results -o allure-report --clean

    # -------------------------
    # Deploy to GitHub Pages
    # -------------------------

    - name: Deploy to GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "automation-bot"
        git config --global user.email "automation@bot.com"

        git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages

        cd gh-pages

        git checkout gh-pages || git checkout -b gh-pages

        rm -rf *

        cp -r ../allure-report/* .

        git add .

        git commit -m "Update Allure report" || echo "No changes"

        git push origin gh-pages