name: Automation Framework CI

on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: "CICD job"
        required: true
        default: "false"

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  selenium-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install allure-robotframework
          pip install pyyaml
      
      - name: Create dev environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "BROWSER: ${{ secrets.BROWSER }}" >> variables/env_dev.yaml
          echo "REGISTER_SUCCESS_REDIRECT_LINK: ${{ secrets.REGISTER_SUCCESS_REDIRECT_LINK }}" >> variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "VALID_USERNAME: ${{ secrets.VALID_USERNAME }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_ERROR_MESSAGE: ${{ secrets.INVALID_EMAIL_ERROR_MESSAGE }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V2: ${{ secrets.INVALID_EMAIL_V2 }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V2_ERROR_MESSAGE: ${{ secrets.INVALID_EMAIL_V2_ERROR_MESSAGE }}" >> variables/env_dev.yaml
          echo "REGISTERED_EMAIL: ${{ secrets.REGISTERED_EMAIL }}" >> variables/env_dev.yaml

      - name: Run Selenium
        run: |
          robot --listener allure_robotframework \
          --outputdir output \
          tests/web/selenium

      - name: Upload Selenium Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-allure
          path: output/allure-results



  playwright-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install robotframework
          pip install robotframework-browser
          pip install allure-robotframework

      - name: Init browser
        run: rfbrowser init

      - name: Create dev environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "BROWSER_FOR_PLAYWRIGHT: ${{ secrets.BROWSER_FOR_PLAYWRIGHT }}" >> variables/env_dev.yaml
          echo "HEADLESS: ${{ secrets.HEADLESS }}" >> variables/env_dev.yaml
          echo "VALID_USERNAME: ${{ secrets.VALID_USERNAME }}" >> variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "INVALID_EMAIL_V3: ${{ secrets.INVALID_EMAIL_V3 }}" >> variables/env_dev.yaml
          echo "REGISTER_PASSWORD: ${{ secrets.REGISTER_PASSWORD }}" >> variables/env_dev.yaml

      - name: Run Playwright (Robot)
        run: |
          robot --listener allure_robotframework \
          --outputdir output \
          tests/web/playwright

      - name: Upload Playwright Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-allure
          path: output/allure-results



  playwright-ts-tests:
    if: ${{ github.event.inputs.run_deploy == 'true' }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: |
          npm install
          npm install -D allure-playwright

      - name: Install browser
        run: npx playwright install --with-deps

      - name: Create environment file
        run: |
          mkdir -p variables
          echo "WEBSITE_URL: ${{ secrets.WEBSITE_URL }}" > variables/env_dev.yaml
          echo "VALID_EMAIL: ${{ secrets.VALID_EMAIL }}" >> variables/env_dev.yaml
          echo "VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}" >> variables/env_dev.yaml

      - name: Run tests
        run: |
          npx playwright test --reporter=line,allure-playwright

      - name: Upload TS Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-ts-allure
          path: allure-results



  generate-allure-report:
    if: always()
    needs:
      - selenium-tests
      - playwright-tests
      - playwright-ts-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Download
      - name: Download Selenium
        uses: actions/download-artifact@v4
        with:
          name: selenium-allure
          path: allure-results/selenium
        continue-on-error: true

      - name: Download Playwright
        uses: actions/download-artifact@v4
        with:
          name: playwright-allure
          path: allure-results/playwright
        continue-on-error: true

      - name: Download TS
        uses: actions/download-artifact@v4
        with:
          name: playwright-ts-allure
          path: allure-results/ts
        continue-on-error: true

      # DEBUG (QUAN TRỌNG)
      - name: Debug files
        run: |
          echo "=== ALLURE RESULTS ==="
          ls -R allure-results || true

      # Merge
      - name: Merge
        run: |
          mkdir -p merged-results
          cp -r allure-results/*/* merged-results/ || true

      # Generate report
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install -g allure-commandline

      - name: Generate report
        run: |
          allure generate merged-results -o allure-report --clean

      # Deploy (DÙNG GITHUB_TOKEN)
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages
          cd gh-pages

          git checkout gh-pages || git checkout -b gh-pages

          rm -rf *
          cp -r ../allure-report/* .

          git add .
          git commit -m "Update report" || echo "No changes"
          git push origin gh-pages